server:
  port: 8082

spring:
  application:
    name: urlShortener

com:
  iam:
    foodie:
      shortener:
        database:
          database-name: shortenerdb
          database-url: mongodb://localhost



# General Configuration

expires-date : 10

### General Error Messages

no-data-found: There is no entity with

invalid-url : Invalid URL.

link-expired : Link expired sad!
#springdoc.api-docs.path=/api-docs
#springdoc.swagger-ui.path=/swagger-ui-custom.html        
   
